# Simple deployment used to deploy and manage the app in nigelpoulton/getting-started-k8s:1.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapideploy-pod
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: web-ctrwebapideploy
        image: manishadotnet/k8spratice:webapifordeployk8s
        imagePullPolicy: Always
        ports:
        - containerPort: 8081