apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    app: web
spec:
  containers:
    - name: web-ctr1
      image: manishadotnet/k8spratice:webapifork8s
      ports:
        - containerPort: 8081 
    - name: web-ctr2
      image: manishadotnet/k8spratice:apiforangular
      ports:
        - containerPort: 8080