apiVersion: v1
kind: Pod
metadata:
  name: webapideploy-pod
  labels:
    app: web
spec:
  containers:
    - name: web-ctrwebapideploy
      image: manishadotnet/k8spratice:webapifordeployk8s
      ports:
        - containerPort: 8081